export const THEME_NAME = "Generated by theme-gpt";
export const WORKBENCH_SETTING = "workbench.colorCustomizations";
export const TOKEN_COLOR_SETTING = "editor.tokenColorCustomizations";
export const GPT_MODEL_SETTING = "theme-gpt.gptModel";
export const OPENAI_API_KEY_SETTING = "theme-gpt.openAiApiKey";